### ISSUE TITLE
Tasks For Wali Ullah

### ISSUE THREAD

**Issue by nabeel-siddiqui-14682** [DevOps-47/Online-Mart#10]
**TASKS FOR WALI ULLAH 42318**

Paper Prototype For The Following Tasks:

- [x] Place order page
- [x] splash screen (when a application first starts)
- [x] Home screen page
@wali-ullah-42318

**Comment by nabeel-siddiqui-14682** [comment]
Submitted the non-related work!
