### ISSUE TITLE
Task for Shahzaib Gauhar Khan

### ISSUE THREAD

**Issue by nabeel-siddiqui-14682** [DevOps-47/Online-Mart#3]
### **Task:**
- [x]  Survey Questions (6-7 questions)

- [x]  Client Summary(The client for whom the work will be done)
- [x]  Team Summary
- [x]  Preliminary requirements analysis

- [x] Gantt Chart
@Shahzaib-Gauhar-Khan-14944

**Comment by nabeel-siddiqui-14682** [comment]
Tasks Done!
