### ISSUE TITLE
TASK FOR NABEEL SIDDIQUI

### ISSUE THREAD

**Issue by nabeel-siddiqui-14682** [DevOps-47/Online-Mart#8]
**TASKS FOR NABEEL SIDDIQUI 14682**

**Paper Prototypes**
- [x] Proceed to shipping page
- [x] Account setting page
- [x] My orders page
- [x] Sign In page
- [x] Sign Up page
- [x] E-Wallet
- [x] About us page

**WireFrames**
- [x] Sign In page
- [x] Sign Up page
- [x] Categories Page
- [x] My Order Page
- [x] Side Menu Page
- [x] Account Setting Page
- [x] Payment page
- [x] Home Screen Page
- [x] E-Wallet Page

**Wali Ullah Tasks (Re-Write and Re-Done by Nabeel Siddiqui 14682)**

**Paper Prototypes**

- [x] Splash Screen
- [x] Home Screen Page
- [x] Place Order Page

@nabeel-siddiqui-14682

**Comment by nabeel-siddiqui-14682** [comment]
Done
